const EXPLICIT_PROXY_ERROR =
  /PROXY|TUNNEL|CONNECTION_REFUSED|CONNECTION_FAILED|INVALID_AUTH_CREDENTIALS/i

const BEST_EFFORT_TRANSPORT_ERROR = /EMPTY_RESPONSE|TIMED_OUT|CONNECTION_CLOSED|CONNECTION_RESET/i

export const isSupportedProxyFailure = (error: string): boolean =>
  EXPLICIT_PROXY_ERROR.test(error) || BEST_EFFORT_TRANSPORT_ERROR.test(error)
